### ISSUE TITLE
COCO导出,没有instances_val2017.json

### ISSUE THREAD

**Issue by monkeycc** [PaddleCV-SIG/PP-Label#94]
PaddleDetection

coco_detection 
```

metric: COCO
num_classes: 80

TrainDataset:
  !COCODataSet
    image_dir: train2017
    anno_path: annotations/instances_train2017.json
    dataset_dir: dataset/coco
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: val2017
    anno_path: annotations/instances_val2017.json
    dataset_dir: dataset/coco

TestDataset:
  !ImageFolder
    anno_path: annotations/instances_val2017.json # also support txt (like VOC's label_list.txt)
    dataset_dir: dataset/coco # if set, anno_path will be 'dataset_dir/anno_path'

```

我们导出的COCO  没有instances_val2017.json
怎么办~

是直接写 test.json 吗

**Comment by linhandev** [comment]
对。导出有三个json，对应划分的时候三个子集。一个集合下没有图片也会有那个集合的json

**Comment by monkeycc** [comment]
如果我想加上测试集
是不是这样
```
TestDataset:
  !COCODataSet
    image_dir: val2017
    anno_path: test.json
    dataset_dir: dataset/coco
```

或者还是

```
TestDataset:
  !ImageFolder
    anno_path: test.json
    dataset_dir: dataset/coco # if set, anno_path will be 'dataset_dir/anno_path'
```
